INSERT INTO CATEGORY (CATEGORY_ID, NAME) values(1, '치킨');
INSERT INTO CATEGORY (CATEGORY_ID, NAME) values(2, '피자');
INSERT INTO CATEGORY (CATEGORY_ID, NAME) values(3, '햄버거');
INSERT INTO CATEGORY (CATEGORY_ID, NAME) values(4, '스테이크');
INSERT INTO CATEGORY (CATEGORY_ID, NAME) values(5, '닭강정');
INSERT INTO CATEGORY (CATEGORY_ID, NAME) values(6, '핫도그');
INSERT INTO CATEGORY (CATEGORY_ID, NAME) values(7, '아이스크림');